### ISSUE TITLE
How to send a request?

### ISSUE THREAD

**Issue by bwbuchanan** [jonas-schievink/xml-rpc-rs#4]
In Request::call, the request is always posted to the "/" URL.

How does one make an XMLRPC request to a remote server? From reading the source for hyper, I didn't see any straightforward way to bind a hyper::client::Client to a particular base URL... it looks to me like the Client expects absolute URLs to be passed to get(), post(), etc., not relative URLs.

I am thinking that either Request::call needs to be modified to accept a target URL as a parameter, or if the method is actually correct as-is, some example code is needed for how to use it.

Also, I think that the Content-Type header should get set in the post():

`.header(ContentType(Mime(TopLevel::Text, SubLevel::Xml, vec![(Attr::Charset, Value::Utf8)])))`

**Comment by jonas-schievink** [comment]
> In Request::call, the request is always posted to the "/" URL.

Yeah, I hardcoded that, probably misunderstood the spec.

> From reading the source for hyper, I didn't see any straightforward way to bind a hyper::client::Client to a particular base URL

You cannot bind a hyper `Client` to a URL, this has to be done when the request is sent.

`Request::call` should indeed accept a URL, probably unconditionally, since the current behaviour really isn't very useful.

Also :+1: to the Content-Type header.
