### ISSUE TITLE
"Expected Content-Length header, but none was found" on gzip compressed data

### ISSUE THREAD

**Issue by faulesocke** [jonas-schievink/xml-rpc-rs#40]
Some APIs may return gzip compressed data. In such a case, reqwest automatically removes the Content-Length header from the response as it's meaningless (see https://github.com/seanmonstar/reqwest/issues/294). In such a case, xmlrpc still requires the Content-Length header in the response, although it can't be of any use and errors out with the message:

```
Err(Error(TransportError(StringError("expected Content-Length header, but none was found"))))
```

Example code that triggers the erroneous behaviour:

```

extern crate xmlrpc;

use xmlrpc::Request;
use xmlrpc::Value;
use std::collections::BTreeMap;

fn main() {
    const URL: &'static str = "http://api.ote.domrobot.com/xmlrpc/";

    let params = [("user", "foo"), ("pass", "bar")];
    let params: BTreeMap<String, Value> = params
        .into_iter()
        .map::<(String, Value), _>(|(k, v)| ((*k).to_owned(), (*v).into()))
        .collect();

    let req = Request::new("account.login").arg(Value::Struct(params));
    let res = req.call_url(URL);

    println!("Result: {:?}", res);
}
```

Cargo.toml:
```
[dependencies]
xmlrpc = "0.11"
```

As you can inspect (for example with tcpdump), the response originally contained the Content-Length header but it was thrown away by reqwest (see issue link above).

**Comment by jonas-schievink** [comment]
As you can see in http://xmlrpc.scripting.com/spec.html under "Response format", the spec mandates that the header must be present:

> The Content-Type is text/xml. Content-Length must be present and correct.

I decided to be strict with this and explicitly check that the Content-Length header is set [here](https://github.com/jonas-schievink/xml-rpc-rs/blob/27e54dece3b6d2f0202503ba70479a1fe426fa5e/src/transport.rs#L120-L121) (I don't check if it's correct because it's not practical to do there).

However, practically this doesn't matter at all, and the spec doesn't ever talk about compression. The Content-Type requirement seems to imply that compression isn't even supported.

Given that XML-RPC is horribly underspecified and technically many implementations don't adhere to the spec (often in very useful ways), I'm willing to just drop that check (and the documentation mentioning any checked headers).

**Comment by faulesocke** [comment]
At least, the header is set in the original response, but dropped by reqwest. Not sure, if there is a way to check if it ever was there and still get automatic decompression.

AFAIR there was a HTTP request header to tell the server, that you don't support compression. But I don't think, this is the right approach either. Maybe just dropping the check is the right solution.
